import Head from 'next/head'
import Image from 'next/image'
import Splash from '../components/splash/splash'
import globals from '../styles/globals.module.css'
import styles from '../styles/home.module.css'

const bgImage = 'bg.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Splash bg={bgImage}>
        <div className={`${globals.glass} ${styles.home}`}>
          <h1>Selamat datang!</h1>
          <h4>Andika Naufal Hilmy</h4>
          <h5>a.k.a. dawetmaster</h5>
          <p>An undergraduate Informatics student who likes and still trying to tinker things about programming.</p>
          <a href='mailto:andika.naufal48@gmail.com'>Kirimkan aku e-mail!</a>
          <br/>
          <a href='https://www.github.com/dawetmaster'>GitHub</a>
          <br/>
          <a href='https://www.linkedin.com/in/andikahilmy/'>LinkedIn</a>
          <br/>
          <a href='https://www.instagram.com/andhilmy'>Instagram</a>
        </div>
      </Splash>
      
    </div>
  )
}
// <p>Photo by <a href="https://unsplash.com/@tricell1991?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Waranont (Joe)</a> on <a href="https://unsplash.com/?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></p>
