# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # just one version only

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2.4.0
      with: 
        version: latest
      
    - name: Install Required Packages
      run: pnpm i
    
    - name: Build and Export Pages
      run: pnpm run build && pnpm run export
    
    - name: Add .nojekyll file
      run: touch out/.nojekyll
    
    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: out
        commit-message: 'Update Github Page'
        branch: gh-pages
